/**
 * Created by zhujiaye on 2017/7/5.
 */
export const START_SIMULATION = 'START_SIMULATION'
export const STOP_SIMULATION = 'STOP_SIMULATION'
export const START_UPLOADING = 'START_UPLOADING'
export const FINISH_UPLOADING = 'FINISH_UPLOADING'
export const CHECK_CONNECTION = 'CHECK_CONNECTION'
