/**
 * Created by zhujiaye on 2017/7/5.
 */
export const START_SIMULATION = 'START_SIMULATION'
export const STOP_SIMULATION = 'STOP_SIMULATION'
export const START_UPLOADING = 'START_UPLOADING'
export const FINISH_UPLOADING = 'FINISH_UPLOADING'
export const CHECK_CONNECTION = 'CHECK_CONNECTION'
export const NODEMAP_DELETE = 'NODEMAP_DELETE'
export const NODEMAP_ADD = 'NODEMAP_ADD'
export const NODEMAP_SET = 'NODEMAP_SET'
export const LINKMAP_DELETE = 'LINKMAP_DELETE'
export const LINKMAP_ADD = 'LINKMAP_ADD'
export const LINKMAP_SET = 'LINKMAP_SET'
